//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GroupInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GroupInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GroupInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GroupInputs"",
    ""maps"": [
        {
            ""name"": ""BindGroup"",
            ""id"": ""29bd3ffa-edfd-460c-b946-6c7ea9c5f40c"",
            ""actions"": [
                {
                    ""name"": ""BindControlGroup1"",
                    ""type"": ""Button"",
                    ""id"": ""6975af2a-b634-473c-87f8-1dd57b324db0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup2"",
                    ""type"": ""Button"",
                    ""id"": ""174d4838-29e8-4203-9279-614fe9044bd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup3"",
                    ""type"": ""Button"",
                    ""id"": ""f3b3b9a4-9499-4718-8de9-faf6fd8f7990"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup4"",
                    ""type"": ""Button"",
                    ""id"": ""802b9402-604a-48e1-a07d-ab50036acf3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup5"",
                    ""type"": ""Button"",
                    ""id"": ""00cd6b78-0140-4360-be75-2e2fff91e6bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup6"",
                    ""type"": ""Button"",
                    ""id"": ""e1b3d4bf-1f61-4afc-85c9-63bbee1f41bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup7"",
                    ""type"": ""Button"",
                    ""id"": ""3502d187-69d4-468c-aa48-b0ebfa440e56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup8"",
                    ""type"": ""Button"",
                    ""id"": ""c624aea6-9355-4a51-b720-e6dddaa14e6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup9"",
                    ""type"": ""Button"",
                    ""id"": ""94cd924e-552c-488c-b9ed-54324b710242"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BindControlGroup10"",
                    ""type"": ""Button"",
                    ""id"": ""acdcedd5-c8f1-432c-97b1-a49937f57054"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup1"",
                    ""type"": ""Button"",
                    ""id"": ""ff6ba377-6756-494a-961a-8d1235fb50ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup2"",
                    ""type"": ""Button"",
                    ""id"": ""38b76501-7da4-42b5-9601-f7fbefa5363d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup3"",
                    ""type"": ""Button"",
                    ""id"": ""860e01ad-e4ef-4b81-b693-f5c695ed9d31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup4"",
                    ""type"": ""Button"",
                    ""id"": ""84d08295-81bc-4047-92d4-af426f355a7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup5"",
                    ""type"": ""Button"",
                    ""id"": ""5ddecf2e-b5ae-4c43-b8e7-3eac88ea2ca0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup6"",
                    ""type"": ""Button"",
                    ""id"": ""e03d3030-b509-4c4a-bb89-460711221f78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup7"",
                    ""type"": ""Button"",
                    ""id"": ""4928be2e-6674-4f60-aa94-75fa5ca7b273"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup8"",
                    ""type"": ""Button"",
                    ""id"": ""c910ba07-3f37-4de0-9a08-b6f046829525"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup9"",
                    ""type"": ""Button"",
                    ""id"": ""8a0613a4-b27a-4a16-bd04-014f014fc63d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RetreiveControlGroup10"",
                    ""type"": ""Button"",
                    ""id"": ""7441699d-126f-4628-a3a9-5e2190d9f2b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""0a764e79-9a6d-4c65-8252-22f8a45c636a"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""7bd72f7f-2c6f-4f41-b8c1-beeb52b52176"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""19ac53b5-8f5f-4710-98ca-2c844d647d54"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dd09ce87-3108-4b01-8cc3-4d6005c2e722"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""48c2cf55-11d0-414e-99a8-163807660c16"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""7ab68380-c47f-468a-a71a-a1754ae8d727"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""bb31bf21-200c-4fa0-b7e1-15809d7a7a59"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d773ca6c-f6d4-4e21-bfa0-99eb17a4f26c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""a83aa8da-118d-49d4-8eb4-9aaad9a9e3e1"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""98e719af-d222-4939-9f47-e5426fe953d0"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""63b8b599-50d1-4ccb-98d7-d2ba1a7134e2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""27acd289-ec8b-4fc7-9183-a18cc3fb5917"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""75f6ce23-61f6-41cb-9b41-aedd1bf0638e"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""e430340c-98de-4e14-9a7e-4a7adaea94d4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""1bac960a-d092-4521-a998-96a3fe3d22c2"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""c6e01193-1c7e-4775-b36e-800ad56d9392"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""0a32e464-3fec-4334-81fb-f3889e07fd6d"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""265417c7-17c3-49ae-bbd3-b7bfc457dc5c"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup6"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""bd2d1931-af27-434f-81b9-46ffe224cda7"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""b195b464-ef11-410b-a756-287770275c2f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""ddf0eb7a-1d6d-43e7-824c-4bd2edd2c10c"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup7"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""4f1d58a0-cbd3-4118-ae7f-e7db67984500"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""cc17c0d3-c408-4fb3-924a-3ebb15625f89"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""4c2681ee-a1ca-4eff-86ae-ed07a51b1cb3"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup8"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""9e1e1d9f-436c-4121-a2aa-9be559db5147"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""5c4eff74-79bd-4a2c-b3cd-56e33044cd1b"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""cf93b788-ea72-4ba9-8ca6-fe51ac275389"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup9"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""40d3a94b-e494-4a4e-9ca5-3187444dd631"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""29f86b82-38cd-41a3-907d-02fb1138ec47"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""010bf1fa-c75b-43bd-be29-0eb918b237d8"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BindControlGroup10"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""cd02c5d0-6dd7-4374-bb46-6c6aaa303452"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""7488099b-8f46-4e37-a51d-f43b4e8ddc50"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""BindControlGroup10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9d85dd81-49de-4a6f-8f16-f4ef8d6b5131"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99af76fd-121f-4912-9c82-ef433742af0b"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""289a9d4d-44d3-474b-9e7e-ddb91f27a4b1"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1908750c-db1f-4500-88cc-c779d0781b2a"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c86393c2-07db-448b-97f3-cabb4e4e43a3"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2ac65ee-0de2-43ba-b813-7db370b0a739"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cefd2c1a-0f22-4eea-98f3-48759c99d6de"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1540c87-3358-403e-9206-4a13b6f401a3"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""RetreiveControlGroup10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Tactical"",
            ""id"": ""b2a6348c-db91-4352-9547-1e34e1ae2ff4"",
            ""actions"": [
                {
                    ""name"": ""ShowTactics"",
                    ""type"": ""Button"",
                    ""id"": ""8852bd7b-4301-4c8d-95f6-46e4e20a8840"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""23425199-cb6b-4870-a544-7a8be5b63e66"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a11a6510-4e80-4d09-8dfe-e361d5f566e9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowTactics"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""13f87fb4-a909-4829-a8a7-7244d3338917"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowTactics"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7b0ac002-8634-4dd3-a545-b2b0e09f3d83"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowTactics"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3b3756b1-4337-49c6-8d72-c6cc2e0a0849"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Touch;XR"",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbfe7622-3c15-414b-b26d-1faddcc4aafd"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // BindGroup
        m_BindGroup = asset.FindActionMap("BindGroup", throwIfNotFound: true);
        m_BindGroup_BindControlGroup1 = m_BindGroup.FindAction("BindControlGroup1", throwIfNotFound: true);
        m_BindGroup_BindControlGroup2 = m_BindGroup.FindAction("BindControlGroup2", throwIfNotFound: true);
        m_BindGroup_BindControlGroup3 = m_BindGroup.FindAction("BindControlGroup3", throwIfNotFound: true);
        m_BindGroup_BindControlGroup4 = m_BindGroup.FindAction("BindControlGroup4", throwIfNotFound: true);
        m_BindGroup_BindControlGroup5 = m_BindGroup.FindAction("BindControlGroup5", throwIfNotFound: true);
        m_BindGroup_BindControlGroup6 = m_BindGroup.FindAction("BindControlGroup6", throwIfNotFound: true);
        m_BindGroup_BindControlGroup7 = m_BindGroup.FindAction("BindControlGroup7", throwIfNotFound: true);
        m_BindGroup_BindControlGroup8 = m_BindGroup.FindAction("BindControlGroup8", throwIfNotFound: true);
        m_BindGroup_BindControlGroup9 = m_BindGroup.FindAction("BindControlGroup9", throwIfNotFound: true);
        m_BindGroup_BindControlGroup10 = m_BindGroup.FindAction("BindControlGroup10", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup1 = m_BindGroup.FindAction("RetreiveControlGroup1", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup2 = m_BindGroup.FindAction("RetreiveControlGroup2", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup3 = m_BindGroup.FindAction("RetreiveControlGroup3", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup4 = m_BindGroup.FindAction("RetreiveControlGroup4", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup5 = m_BindGroup.FindAction("RetreiveControlGroup5", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup6 = m_BindGroup.FindAction("RetreiveControlGroup6", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup7 = m_BindGroup.FindAction("RetreiveControlGroup7", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup8 = m_BindGroup.FindAction("RetreiveControlGroup8", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup9 = m_BindGroup.FindAction("RetreiveControlGroup9", throwIfNotFound: true);
        m_BindGroup_RetreiveControlGroup10 = m_BindGroup.FindAction("RetreiveControlGroup10", throwIfNotFound: true);
        // Tactical
        m_Tactical = asset.FindActionMap("Tactical", throwIfNotFound: true);
        m_Tactical_ShowTactics = m_Tactical.FindAction("ShowTactics", throwIfNotFound: true);
        m_Tactical_CursorPosition = m_Tactical.FindAction("CursorPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BindGroup
    private readonly InputActionMap m_BindGroup;
    private List<IBindGroupActions> m_BindGroupActionsCallbackInterfaces = new List<IBindGroupActions>();
    private readonly InputAction m_BindGroup_BindControlGroup1;
    private readonly InputAction m_BindGroup_BindControlGroup2;
    private readonly InputAction m_BindGroup_BindControlGroup3;
    private readonly InputAction m_BindGroup_BindControlGroup4;
    private readonly InputAction m_BindGroup_BindControlGroup5;
    private readonly InputAction m_BindGroup_BindControlGroup6;
    private readonly InputAction m_BindGroup_BindControlGroup7;
    private readonly InputAction m_BindGroup_BindControlGroup8;
    private readonly InputAction m_BindGroup_BindControlGroup9;
    private readonly InputAction m_BindGroup_BindControlGroup10;
    private readonly InputAction m_BindGroup_RetreiveControlGroup1;
    private readonly InputAction m_BindGroup_RetreiveControlGroup2;
    private readonly InputAction m_BindGroup_RetreiveControlGroup3;
    private readonly InputAction m_BindGroup_RetreiveControlGroup4;
    private readonly InputAction m_BindGroup_RetreiveControlGroup5;
    private readonly InputAction m_BindGroup_RetreiveControlGroup6;
    private readonly InputAction m_BindGroup_RetreiveControlGroup7;
    private readonly InputAction m_BindGroup_RetreiveControlGroup8;
    private readonly InputAction m_BindGroup_RetreiveControlGroup9;
    private readonly InputAction m_BindGroup_RetreiveControlGroup10;
    public struct BindGroupActions
    {
        private @GroupInputs m_Wrapper;
        public BindGroupActions(@GroupInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @BindControlGroup1 => m_Wrapper.m_BindGroup_BindControlGroup1;
        public InputAction @BindControlGroup2 => m_Wrapper.m_BindGroup_BindControlGroup2;
        public InputAction @BindControlGroup3 => m_Wrapper.m_BindGroup_BindControlGroup3;
        public InputAction @BindControlGroup4 => m_Wrapper.m_BindGroup_BindControlGroup4;
        public InputAction @BindControlGroup5 => m_Wrapper.m_BindGroup_BindControlGroup5;
        public InputAction @BindControlGroup6 => m_Wrapper.m_BindGroup_BindControlGroup6;
        public InputAction @BindControlGroup7 => m_Wrapper.m_BindGroup_BindControlGroup7;
        public InputAction @BindControlGroup8 => m_Wrapper.m_BindGroup_BindControlGroup8;
        public InputAction @BindControlGroup9 => m_Wrapper.m_BindGroup_BindControlGroup9;
        public InputAction @BindControlGroup10 => m_Wrapper.m_BindGroup_BindControlGroup10;
        public InputAction @RetreiveControlGroup1 => m_Wrapper.m_BindGroup_RetreiveControlGroup1;
        public InputAction @RetreiveControlGroup2 => m_Wrapper.m_BindGroup_RetreiveControlGroup2;
        public InputAction @RetreiveControlGroup3 => m_Wrapper.m_BindGroup_RetreiveControlGroup3;
        public InputAction @RetreiveControlGroup4 => m_Wrapper.m_BindGroup_RetreiveControlGroup4;
        public InputAction @RetreiveControlGroup5 => m_Wrapper.m_BindGroup_RetreiveControlGroup5;
        public InputAction @RetreiveControlGroup6 => m_Wrapper.m_BindGroup_RetreiveControlGroup6;
        public InputAction @RetreiveControlGroup7 => m_Wrapper.m_BindGroup_RetreiveControlGroup7;
        public InputAction @RetreiveControlGroup8 => m_Wrapper.m_BindGroup_RetreiveControlGroup8;
        public InputAction @RetreiveControlGroup9 => m_Wrapper.m_BindGroup_RetreiveControlGroup9;
        public InputAction @RetreiveControlGroup10 => m_Wrapper.m_BindGroup_RetreiveControlGroup10;
        public InputActionMap Get() { return m_Wrapper.m_BindGroup; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BindGroupActions set) { return set.Get(); }
        public void AddCallbacks(IBindGroupActions instance)
        {
            if (instance == null || m_Wrapper.m_BindGroupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BindGroupActionsCallbackInterfaces.Add(instance);
            @BindControlGroup1.started += instance.OnBindControlGroup1;
            @BindControlGroup1.performed += instance.OnBindControlGroup1;
            @BindControlGroup1.canceled += instance.OnBindControlGroup1;
            @BindControlGroup2.started += instance.OnBindControlGroup2;
            @BindControlGroup2.performed += instance.OnBindControlGroup2;
            @BindControlGroup2.canceled += instance.OnBindControlGroup2;
            @BindControlGroup3.started += instance.OnBindControlGroup3;
            @BindControlGroup3.performed += instance.OnBindControlGroup3;
            @BindControlGroup3.canceled += instance.OnBindControlGroup3;
            @BindControlGroup4.started += instance.OnBindControlGroup4;
            @BindControlGroup4.performed += instance.OnBindControlGroup4;
            @BindControlGroup4.canceled += instance.OnBindControlGroup4;
            @BindControlGroup5.started += instance.OnBindControlGroup5;
            @BindControlGroup5.performed += instance.OnBindControlGroup5;
            @BindControlGroup5.canceled += instance.OnBindControlGroup5;
            @BindControlGroup6.started += instance.OnBindControlGroup6;
            @BindControlGroup6.performed += instance.OnBindControlGroup6;
            @BindControlGroup6.canceled += instance.OnBindControlGroup6;
            @BindControlGroup7.started += instance.OnBindControlGroup7;
            @BindControlGroup7.performed += instance.OnBindControlGroup7;
            @BindControlGroup7.canceled += instance.OnBindControlGroup7;
            @BindControlGroup8.started += instance.OnBindControlGroup8;
            @BindControlGroup8.performed += instance.OnBindControlGroup8;
            @BindControlGroup8.canceled += instance.OnBindControlGroup8;
            @BindControlGroup9.started += instance.OnBindControlGroup9;
            @BindControlGroup9.performed += instance.OnBindControlGroup9;
            @BindControlGroup9.canceled += instance.OnBindControlGroup9;
            @BindControlGroup10.started += instance.OnBindControlGroup10;
            @BindControlGroup10.performed += instance.OnBindControlGroup10;
            @BindControlGroup10.canceled += instance.OnBindControlGroup10;
            @RetreiveControlGroup1.started += instance.OnRetreiveControlGroup1;
            @RetreiveControlGroup1.performed += instance.OnRetreiveControlGroup1;
            @RetreiveControlGroup1.canceled += instance.OnRetreiveControlGroup1;
            @RetreiveControlGroup2.started += instance.OnRetreiveControlGroup2;
            @RetreiveControlGroup2.performed += instance.OnRetreiveControlGroup2;
            @RetreiveControlGroup2.canceled += instance.OnRetreiveControlGroup2;
            @RetreiveControlGroup3.started += instance.OnRetreiveControlGroup3;
            @RetreiveControlGroup3.performed += instance.OnRetreiveControlGroup3;
            @RetreiveControlGroup3.canceled += instance.OnRetreiveControlGroup3;
            @RetreiveControlGroup4.started += instance.OnRetreiveControlGroup4;
            @RetreiveControlGroup4.performed += instance.OnRetreiveControlGroup4;
            @RetreiveControlGroup4.canceled += instance.OnRetreiveControlGroup4;
            @RetreiveControlGroup5.started += instance.OnRetreiveControlGroup5;
            @RetreiveControlGroup5.performed += instance.OnRetreiveControlGroup5;
            @RetreiveControlGroup5.canceled += instance.OnRetreiveControlGroup5;
            @RetreiveControlGroup6.started += instance.OnRetreiveControlGroup6;
            @RetreiveControlGroup6.performed += instance.OnRetreiveControlGroup6;
            @RetreiveControlGroup6.canceled += instance.OnRetreiveControlGroup6;
            @RetreiveControlGroup7.started += instance.OnRetreiveControlGroup7;
            @RetreiveControlGroup7.performed += instance.OnRetreiveControlGroup7;
            @RetreiveControlGroup7.canceled += instance.OnRetreiveControlGroup7;
            @RetreiveControlGroup8.started += instance.OnRetreiveControlGroup8;
            @RetreiveControlGroup8.performed += instance.OnRetreiveControlGroup8;
            @RetreiveControlGroup8.canceled += instance.OnRetreiveControlGroup8;
            @RetreiveControlGroup9.started += instance.OnRetreiveControlGroup9;
            @RetreiveControlGroup9.performed += instance.OnRetreiveControlGroup9;
            @RetreiveControlGroup9.canceled += instance.OnRetreiveControlGroup9;
            @RetreiveControlGroup10.started += instance.OnRetreiveControlGroup10;
            @RetreiveControlGroup10.performed += instance.OnRetreiveControlGroup10;
            @RetreiveControlGroup10.canceled += instance.OnRetreiveControlGroup10;
        }

        private void UnregisterCallbacks(IBindGroupActions instance)
        {
            @BindControlGroup1.started -= instance.OnBindControlGroup1;
            @BindControlGroup1.performed -= instance.OnBindControlGroup1;
            @BindControlGroup1.canceled -= instance.OnBindControlGroup1;
            @BindControlGroup2.started -= instance.OnBindControlGroup2;
            @BindControlGroup2.performed -= instance.OnBindControlGroup2;
            @BindControlGroup2.canceled -= instance.OnBindControlGroup2;
            @BindControlGroup3.started -= instance.OnBindControlGroup3;
            @BindControlGroup3.performed -= instance.OnBindControlGroup3;
            @BindControlGroup3.canceled -= instance.OnBindControlGroup3;
            @BindControlGroup4.started -= instance.OnBindControlGroup4;
            @BindControlGroup4.performed -= instance.OnBindControlGroup4;
            @BindControlGroup4.canceled -= instance.OnBindControlGroup4;
            @BindControlGroup5.started -= instance.OnBindControlGroup5;
            @BindControlGroup5.performed -= instance.OnBindControlGroup5;
            @BindControlGroup5.canceled -= instance.OnBindControlGroup5;
            @BindControlGroup6.started -= instance.OnBindControlGroup6;
            @BindControlGroup6.performed -= instance.OnBindControlGroup6;
            @BindControlGroup6.canceled -= instance.OnBindControlGroup6;
            @BindControlGroup7.started -= instance.OnBindControlGroup7;
            @BindControlGroup7.performed -= instance.OnBindControlGroup7;
            @BindControlGroup7.canceled -= instance.OnBindControlGroup7;
            @BindControlGroup8.started -= instance.OnBindControlGroup8;
            @BindControlGroup8.performed -= instance.OnBindControlGroup8;
            @BindControlGroup8.canceled -= instance.OnBindControlGroup8;
            @BindControlGroup9.started -= instance.OnBindControlGroup9;
            @BindControlGroup9.performed -= instance.OnBindControlGroup9;
            @BindControlGroup9.canceled -= instance.OnBindControlGroup9;
            @BindControlGroup10.started -= instance.OnBindControlGroup10;
            @BindControlGroup10.performed -= instance.OnBindControlGroup10;
            @BindControlGroup10.canceled -= instance.OnBindControlGroup10;
            @RetreiveControlGroup1.started -= instance.OnRetreiveControlGroup1;
            @RetreiveControlGroup1.performed -= instance.OnRetreiveControlGroup1;
            @RetreiveControlGroup1.canceled -= instance.OnRetreiveControlGroup1;
            @RetreiveControlGroup2.started -= instance.OnRetreiveControlGroup2;
            @RetreiveControlGroup2.performed -= instance.OnRetreiveControlGroup2;
            @RetreiveControlGroup2.canceled -= instance.OnRetreiveControlGroup2;
            @RetreiveControlGroup3.started -= instance.OnRetreiveControlGroup3;
            @RetreiveControlGroup3.performed -= instance.OnRetreiveControlGroup3;
            @RetreiveControlGroup3.canceled -= instance.OnRetreiveControlGroup3;
            @RetreiveControlGroup4.started -= instance.OnRetreiveControlGroup4;
            @RetreiveControlGroup4.performed -= instance.OnRetreiveControlGroup4;
            @RetreiveControlGroup4.canceled -= instance.OnRetreiveControlGroup4;
            @RetreiveControlGroup5.started -= instance.OnRetreiveControlGroup5;
            @RetreiveControlGroup5.performed -= instance.OnRetreiveControlGroup5;
            @RetreiveControlGroup5.canceled -= instance.OnRetreiveControlGroup5;
            @RetreiveControlGroup6.started -= instance.OnRetreiveControlGroup6;
            @RetreiveControlGroup6.performed -= instance.OnRetreiveControlGroup6;
            @RetreiveControlGroup6.canceled -= instance.OnRetreiveControlGroup6;
            @RetreiveControlGroup7.started -= instance.OnRetreiveControlGroup7;
            @RetreiveControlGroup7.performed -= instance.OnRetreiveControlGroup7;
            @RetreiveControlGroup7.canceled -= instance.OnRetreiveControlGroup7;
            @RetreiveControlGroup8.started -= instance.OnRetreiveControlGroup8;
            @RetreiveControlGroup8.performed -= instance.OnRetreiveControlGroup8;
            @RetreiveControlGroup8.canceled -= instance.OnRetreiveControlGroup8;
            @RetreiveControlGroup9.started -= instance.OnRetreiveControlGroup9;
            @RetreiveControlGroup9.performed -= instance.OnRetreiveControlGroup9;
            @RetreiveControlGroup9.canceled -= instance.OnRetreiveControlGroup9;
            @RetreiveControlGroup10.started -= instance.OnRetreiveControlGroup10;
            @RetreiveControlGroup10.performed -= instance.OnRetreiveControlGroup10;
            @RetreiveControlGroup10.canceled -= instance.OnRetreiveControlGroup10;
        }

        public void RemoveCallbacks(IBindGroupActions instance)
        {
            if (m_Wrapper.m_BindGroupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBindGroupActions instance)
        {
            foreach (var item in m_Wrapper.m_BindGroupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BindGroupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BindGroupActions @BindGroup => new BindGroupActions(this);

    // Tactical
    private readonly InputActionMap m_Tactical;
    private List<ITacticalActions> m_TacticalActionsCallbackInterfaces = new List<ITacticalActions>();
    private readonly InputAction m_Tactical_ShowTactics;
    private readonly InputAction m_Tactical_CursorPosition;
    public struct TacticalActions
    {
        private @GroupInputs m_Wrapper;
        public TacticalActions(@GroupInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShowTactics => m_Wrapper.m_Tactical_ShowTactics;
        public InputAction @CursorPosition => m_Wrapper.m_Tactical_CursorPosition;
        public InputActionMap Get() { return m_Wrapper.m_Tactical; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TacticalActions set) { return set.Get(); }
        public void AddCallbacks(ITacticalActions instance)
        {
            if (instance == null || m_Wrapper.m_TacticalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TacticalActionsCallbackInterfaces.Add(instance);
            @ShowTactics.started += instance.OnShowTactics;
            @ShowTactics.performed += instance.OnShowTactics;
            @ShowTactics.canceled += instance.OnShowTactics;
            @CursorPosition.started += instance.OnCursorPosition;
            @CursorPosition.performed += instance.OnCursorPosition;
            @CursorPosition.canceled += instance.OnCursorPosition;
        }

        private void UnregisterCallbacks(ITacticalActions instance)
        {
            @ShowTactics.started -= instance.OnShowTactics;
            @ShowTactics.performed -= instance.OnShowTactics;
            @ShowTactics.canceled -= instance.OnShowTactics;
            @CursorPosition.started -= instance.OnCursorPosition;
            @CursorPosition.performed -= instance.OnCursorPosition;
            @CursorPosition.canceled -= instance.OnCursorPosition;
        }

        public void RemoveCallbacks(ITacticalActions instance)
        {
            if (m_Wrapper.m_TacticalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITacticalActions instance)
        {
            foreach (var item in m_Wrapper.m_TacticalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TacticalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TacticalActions @Tactical => new TacticalActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IBindGroupActions
    {
        void OnBindControlGroup1(InputAction.CallbackContext context);
        void OnBindControlGroup2(InputAction.CallbackContext context);
        void OnBindControlGroup3(InputAction.CallbackContext context);
        void OnBindControlGroup4(InputAction.CallbackContext context);
        void OnBindControlGroup5(InputAction.CallbackContext context);
        void OnBindControlGroup6(InputAction.CallbackContext context);
        void OnBindControlGroup7(InputAction.CallbackContext context);
        void OnBindControlGroup8(InputAction.CallbackContext context);
        void OnBindControlGroup9(InputAction.CallbackContext context);
        void OnBindControlGroup10(InputAction.CallbackContext context);
        void OnRetreiveControlGroup1(InputAction.CallbackContext context);
        void OnRetreiveControlGroup2(InputAction.CallbackContext context);
        void OnRetreiveControlGroup3(InputAction.CallbackContext context);
        void OnRetreiveControlGroup4(InputAction.CallbackContext context);
        void OnRetreiveControlGroup5(InputAction.CallbackContext context);
        void OnRetreiveControlGroup6(InputAction.CallbackContext context);
        void OnRetreiveControlGroup7(InputAction.CallbackContext context);
        void OnRetreiveControlGroup8(InputAction.CallbackContext context);
        void OnRetreiveControlGroup9(InputAction.CallbackContext context);
        void OnRetreiveControlGroup10(InputAction.CallbackContext context);
    }
    public interface ITacticalActions
    {
        void OnShowTactics(InputAction.CallbackContext context);
        void OnCursorPosition(InputAction.CallbackContext context);
    }
}
