//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""007e42db-7569-454b-883f-2eb939fc9867"",
            ""actions"": [
                {
                    ""name"": ""Yaw"",
                    ""type"": ""Button"",
                    ""id"": ""de0edc6c-1575-412d-be5b-2c4fd05f75de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pitch"",
                    ""type"": ""Value"",
                    ""id"": ""a6415955-82ec-4967-be33-baea5ee1ec28"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RTSView"",
                    ""type"": ""Button"",
                    ""id"": ""72d835d1-297a-47dc-9f16-b3a453a60bf3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XZMove"",
                    ""type"": ""Value"",
                    ""id"": ""65622dd2-22d1-46d2-8ca4-0a0b92b8f615"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YMove"",
                    ""type"": ""Value"",
                    ""id"": ""9bc5fcd1-bd7c-4376-9025-8e6be440ee95"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MiddleMouseMove"",
                    ""type"": ""Value"",
                    ""id"": ""5bab7b5d-f7ea-4587-9cc5-9282d8f8e716"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f1d2b214-1356-42e3-84f3-a8f6fbe14cfd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3e542e2d-30f3-4e1d-9040-e6ae6b9b9478"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""96d7d09c-7637-4929-ac13-d6629f4b61c2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""febf30af-f1ce-42b4-8099-3e9411c077df"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a4efc5ef-743f-46c9-9af1-64ea34b7f4d0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c9e51cd0-362a-4650-948e-14b7e5e016c5"",
                    ""path"": ""<Keyboard>/#(Z)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6d8821c4-1fe4-4fa5-9a3e-45cd38998f95"",
                    ""path"": ""<Keyboard>/#(X)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f59b68c2-5339-4f13-b940-f437d8fbb03c"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d567df77-bedc-4d13-be09-1fe3f9763e05"",
                    ""path"": ""<Keyboard>/#(C)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTSView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""050ae0b9-b24a-484a-8a75-63bced435314"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7a43725-4a53-4214-806d-2865ed2e92d1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e2db6342-0fa9-4da7-b13d-8b68c7790cf2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""102bbe4e-263c-4c2a-97af-88bc69860463"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d1555d69-1bac-41fa-83ba-c0722b2cf04a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b85cd45d-dbaf-4df0-930d-b0a3ab0c8ebb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d7516bec-c54f-4ae8-93ae-323093ccf2b6"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7ecc6bef-4927-400b-974b-b8d9bd7b6ab0"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""02b92c07-1979-4d39-8e0b-b2e66976bef8"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1add975a-bcd1-45e9-81cb-1304704c2072"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f6e1afcd-69bc-4bd6-8636-ac6d0ca5a432"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a29c0cf3-da2d-440b-9085-43e8cc1fcf0e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b9b3c265-84a0-4748-8ba1-7e5dba9a4a42"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0479ed73-b52b-48c0-a742-193f6a5ef6dd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""89ac881b-cbfa-4e19-9bc1-a1ece087fd86"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c119b839-9411-4736-8daf-6958d47178f9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5d7485be-e1b9-4aeb-b0c0-a32dcb90d4a4"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e4f6a117-423c-4fc2-8811-e22acfffe3a6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XZMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8e17f1cf-109c-460a-9c92-d034e8d4c9e9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""10685d90-0117-452c-9173-d79f41cdaadc"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""c3050eb7-ff47-4b13-bd70-edeb2e28f7ac"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a4fc04fb-a560-47cc-9341-9a1e0eca188e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""642f8c5e-e368-42d9-8114-cd8eeddc07ba"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""82c2367e-3c65-43d2-98fd-64fc118bbbee"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""773e73eb-b501-47c0-a0f1-f72be94128a5"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(y=-0.025)"",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""72f257a9-cffc-4fea-8d7c-27fa9b68df6e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2"",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb9ab9b7-21ea-479c-908a-c74295fada7c"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""951b5f09-3823-44d6-b71c-f03327b83253"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""617e1a54-124e-4587-838f-f0978308da9d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleMouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Entities"",
            ""id"": ""ec6ada94-8152-4f10-a9b2-43ed64b711dc"",
            ""actions"": [
                {
                    ""name"": ""Speed"",
                    ""type"": ""Value"",
                    ""id"": ""66d77813-00f7-4adb-8991-861c0a26e919"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Heading"",
                    ""type"": ""Button"",
                    ""id"": ""41f804a4-fc86-4150-bc55-563ccf23bf12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Command"",
                    ""type"": ""Button"",
                    ""id"": ""0217ed2a-6e62-47db-89c1-992ce1eebddf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Intercept"",
                    ""type"": ""Button"",
                    ""id"": ""f965f433-ee4c-427b-9cd2-7258f9c92b74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Create100"",
                    ""type"": ""Button"",
                    ""id"": ""2fa46691-b915-4755-8db5-7aba03303154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddCommand"",
                    ""type"": ""Button"",
                    ""id"": ""76ce0ced-7cb1-4836-a722-c87dc1a2fa07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""96ec8e28-58cb-4d05-98b0-87da4816747c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""21efad6b-f1e3-4b7a-a79a-40bc0fe2a0c3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""153a734f-6a93-460c-9c4b-9f492fb37ec0"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""0f0dc2a2-ba42-4860-a8e9-6397bfaffa62"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""617655b5-b928-4a4c-a34b-8dd3a1bff474"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b414ad96-478e-426f-b776-573ccdbe74ba"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2dfa1597-c52e-47bd-bcab-4cd9b2548a03"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Command"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f3b0c43-0d06-477a-8db9-0c02948f316f"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Command"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7de1f10-b7d0-4a1d-b982-7077d2aa5609"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Intercept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c73005a-f2bd-4d92-b684-be930de06f0a"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create100"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b197794-b8b7-46a8-a015-f147da1f40a6"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Selection"",
            ""id"": ""ce5509f5-2920-45c3-ac1b-c591f44f94f5"",
            ""actions"": [
                {
                    ""name"": ""ClearSelection"",
                    ""type"": ""Button"",
                    ""id"": ""6ab4753c-7e62-4d31-8890-01181afe430d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""Button"",
                    ""id"": ""d2d504d8-77e7-4511-8ff3-b71ae76aed5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""2a8af9bf-3ad6-470f-99ca-178f6cd0c7bf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NextEntity"",
                    ""type"": ""Button"",
                    ""id"": ""81ca03f9-4618-4769-a171-377045b18430"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""25139539-d122-4edd-86fb-a80a2e765d93"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02b1074a-c5ca-429f-b410-108e86d6ffbc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7aa1c846-c9f7-4915-95be-d0807b1af1fe"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""SlowTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b65f60b6-13e2-4dae-8656-46815aebf3ed"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1b257ae-ce74-4e3a-8ce1-2a15c05be945"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f1ce320-bf01-4f60-b382-115472fd5122"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextEntity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Yaw = m_Camera.FindAction("Yaw", throwIfNotFound: true);
        m_Camera_Pitch = m_Camera.FindAction("Pitch", throwIfNotFound: true);
        m_Camera_RTSView = m_Camera.FindAction("RTSView", throwIfNotFound: true);
        m_Camera_XZMove = m_Camera.FindAction("XZMove", throwIfNotFound: true);
        m_Camera_YMove = m_Camera.FindAction("YMove", throwIfNotFound: true);
        m_Camera_MiddleMouseMove = m_Camera.FindAction("MiddleMouseMove", throwIfNotFound: true);
        // Entities
        m_Entities = asset.FindActionMap("Entities", throwIfNotFound: true);
        m_Entities_Speed = m_Entities.FindAction("Speed", throwIfNotFound: true);
        m_Entities_Heading = m_Entities.FindAction("Heading", throwIfNotFound: true);
        m_Entities_Command = m_Entities.FindAction("Command", throwIfNotFound: true);
        m_Entities_Intercept = m_Entities.FindAction("Intercept", throwIfNotFound: true);
        m_Entities_Create100 = m_Entities.FindAction("Create100", throwIfNotFound: true);
        m_Entities_AddCommand = m_Entities.FindAction("AddCommand", throwIfNotFound: true);
        // Selection
        m_Selection = asset.FindActionMap("Selection", throwIfNotFound: true);
        m_Selection_ClearSelection = m_Selection.FindAction("ClearSelection", throwIfNotFound: true);
        m_Selection_Cursor = m_Selection.FindAction("Cursor", throwIfNotFound: true);
        m_Selection_CursorPosition = m_Selection.FindAction("CursorPosition", throwIfNotFound: true);
        m_Selection_NextEntity = m_Selection.FindAction("NextEntity", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_Yaw;
    private readonly InputAction m_Camera_Pitch;
    private readonly InputAction m_Camera_RTSView;
    private readonly InputAction m_Camera_XZMove;
    private readonly InputAction m_Camera_YMove;
    private readonly InputAction m_Camera_MiddleMouseMove;
    public struct CameraActions
    {
        private @GameInputs m_Wrapper;
        public CameraActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Yaw => m_Wrapper.m_Camera_Yaw;
        public InputAction @Pitch => m_Wrapper.m_Camera_Pitch;
        public InputAction @RTSView => m_Wrapper.m_Camera_RTSView;
        public InputAction @XZMove => m_Wrapper.m_Camera_XZMove;
        public InputAction @YMove => m_Wrapper.m_Camera_YMove;
        public InputAction @MiddleMouseMove => m_Wrapper.m_Camera_MiddleMouseMove;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @Yaw.started += instance.OnYaw;
            @Yaw.performed += instance.OnYaw;
            @Yaw.canceled += instance.OnYaw;
            @Pitch.started += instance.OnPitch;
            @Pitch.performed += instance.OnPitch;
            @Pitch.canceled += instance.OnPitch;
            @RTSView.started += instance.OnRTSView;
            @RTSView.performed += instance.OnRTSView;
            @RTSView.canceled += instance.OnRTSView;
            @XZMove.started += instance.OnXZMove;
            @XZMove.performed += instance.OnXZMove;
            @XZMove.canceled += instance.OnXZMove;
            @YMove.started += instance.OnYMove;
            @YMove.performed += instance.OnYMove;
            @YMove.canceled += instance.OnYMove;
            @MiddleMouseMove.started += instance.OnMiddleMouseMove;
            @MiddleMouseMove.performed += instance.OnMiddleMouseMove;
            @MiddleMouseMove.canceled += instance.OnMiddleMouseMove;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @Yaw.started -= instance.OnYaw;
            @Yaw.performed -= instance.OnYaw;
            @Yaw.canceled -= instance.OnYaw;
            @Pitch.started -= instance.OnPitch;
            @Pitch.performed -= instance.OnPitch;
            @Pitch.canceled -= instance.OnPitch;
            @RTSView.started -= instance.OnRTSView;
            @RTSView.performed -= instance.OnRTSView;
            @RTSView.canceled -= instance.OnRTSView;
            @XZMove.started -= instance.OnXZMove;
            @XZMove.performed -= instance.OnXZMove;
            @XZMove.canceled -= instance.OnXZMove;
            @YMove.started -= instance.OnYMove;
            @YMove.performed -= instance.OnYMove;
            @YMove.canceled -= instance.OnYMove;
            @MiddleMouseMove.started -= instance.OnMiddleMouseMove;
            @MiddleMouseMove.performed -= instance.OnMiddleMouseMove;
            @MiddleMouseMove.canceled -= instance.OnMiddleMouseMove;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // Entities
    private readonly InputActionMap m_Entities;
    private List<IEntitiesActions> m_EntitiesActionsCallbackInterfaces = new List<IEntitiesActions>();
    private readonly InputAction m_Entities_Speed;
    private readonly InputAction m_Entities_Heading;
    private readonly InputAction m_Entities_Command;
    private readonly InputAction m_Entities_Intercept;
    private readonly InputAction m_Entities_Create100;
    private readonly InputAction m_Entities_AddCommand;
    public struct EntitiesActions
    {
        private @GameInputs m_Wrapper;
        public EntitiesActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Speed => m_Wrapper.m_Entities_Speed;
        public InputAction @Heading => m_Wrapper.m_Entities_Heading;
        public InputAction @Command => m_Wrapper.m_Entities_Command;
        public InputAction @Intercept => m_Wrapper.m_Entities_Intercept;
        public InputAction @Create100 => m_Wrapper.m_Entities_Create100;
        public InputAction @AddCommand => m_Wrapper.m_Entities_AddCommand;
        public InputActionMap Get() { return m_Wrapper.m_Entities; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EntitiesActions set) { return set.Get(); }
        public void AddCallbacks(IEntitiesActions instance)
        {
            if (instance == null || m_Wrapper.m_EntitiesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EntitiesActionsCallbackInterfaces.Add(instance);
            @Speed.started += instance.OnSpeed;
            @Speed.performed += instance.OnSpeed;
            @Speed.canceled += instance.OnSpeed;
            @Heading.started += instance.OnHeading;
            @Heading.performed += instance.OnHeading;
            @Heading.canceled += instance.OnHeading;
            @Command.started += instance.OnCommand;
            @Command.performed += instance.OnCommand;
            @Command.canceled += instance.OnCommand;
            @Intercept.started += instance.OnIntercept;
            @Intercept.performed += instance.OnIntercept;
            @Intercept.canceled += instance.OnIntercept;
            @Create100.started += instance.OnCreate100;
            @Create100.performed += instance.OnCreate100;
            @Create100.canceled += instance.OnCreate100;
            @AddCommand.started += instance.OnAddCommand;
            @AddCommand.performed += instance.OnAddCommand;
            @AddCommand.canceled += instance.OnAddCommand;
        }

        private void UnregisterCallbacks(IEntitiesActions instance)
        {
            @Speed.started -= instance.OnSpeed;
            @Speed.performed -= instance.OnSpeed;
            @Speed.canceled -= instance.OnSpeed;
            @Heading.started -= instance.OnHeading;
            @Heading.performed -= instance.OnHeading;
            @Heading.canceled -= instance.OnHeading;
            @Command.started -= instance.OnCommand;
            @Command.performed -= instance.OnCommand;
            @Command.canceled -= instance.OnCommand;
            @Intercept.started -= instance.OnIntercept;
            @Intercept.performed -= instance.OnIntercept;
            @Intercept.canceled -= instance.OnIntercept;
            @Create100.started -= instance.OnCreate100;
            @Create100.performed -= instance.OnCreate100;
            @Create100.canceled -= instance.OnCreate100;
            @AddCommand.started -= instance.OnAddCommand;
            @AddCommand.performed -= instance.OnAddCommand;
            @AddCommand.canceled -= instance.OnAddCommand;
        }

        public void RemoveCallbacks(IEntitiesActions instance)
        {
            if (m_Wrapper.m_EntitiesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEntitiesActions instance)
        {
            foreach (var item in m_Wrapper.m_EntitiesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EntitiesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EntitiesActions @Entities => new EntitiesActions(this);

    // Selection
    private readonly InputActionMap m_Selection;
    private List<ISelectionActions> m_SelectionActionsCallbackInterfaces = new List<ISelectionActions>();
    private readonly InputAction m_Selection_ClearSelection;
    private readonly InputAction m_Selection_Cursor;
    private readonly InputAction m_Selection_CursorPosition;
    private readonly InputAction m_Selection_NextEntity;
    public struct SelectionActions
    {
        private @GameInputs m_Wrapper;
        public SelectionActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClearSelection => m_Wrapper.m_Selection_ClearSelection;
        public InputAction @Cursor => m_Wrapper.m_Selection_Cursor;
        public InputAction @CursorPosition => m_Wrapper.m_Selection_CursorPosition;
        public InputAction @NextEntity => m_Wrapper.m_Selection_NextEntity;
        public InputActionMap Get() { return m_Wrapper.m_Selection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectionActions set) { return set.Get(); }
        public void AddCallbacks(ISelectionActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectionActionsCallbackInterfaces.Add(instance);
            @ClearSelection.started += instance.OnClearSelection;
            @ClearSelection.performed += instance.OnClearSelection;
            @ClearSelection.canceled += instance.OnClearSelection;
            @Cursor.started += instance.OnCursor;
            @Cursor.performed += instance.OnCursor;
            @Cursor.canceled += instance.OnCursor;
            @CursorPosition.started += instance.OnCursorPosition;
            @CursorPosition.performed += instance.OnCursorPosition;
            @CursorPosition.canceled += instance.OnCursorPosition;
            @NextEntity.started += instance.OnNextEntity;
            @NextEntity.performed += instance.OnNextEntity;
            @NextEntity.canceled += instance.OnNextEntity;
        }

        private void UnregisterCallbacks(ISelectionActions instance)
        {
            @ClearSelection.started -= instance.OnClearSelection;
            @ClearSelection.performed -= instance.OnClearSelection;
            @ClearSelection.canceled -= instance.OnClearSelection;
            @Cursor.started -= instance.OnCursor;
            @Cursor.performed -= instance.OnCursor;
            @Cursor.canceled -= instance.OnCursor;
            @CursorPosition.started -= instance.OnCursorPosition;
            @CursorPosition.performed -= instance.OnCursorPosition;
            @CursorPosition.canceled -= instance.OnCursorPosition;
            @NextEntity.started -= instance.OnNextEntity;
            @NextEntity.performed -= instance.OnNextEntity;
            @NextEntity.canceled -= instance.OnNextEntity;
        }

        public void RemoveCallbacks(ISelectionActions instance)
        {
            if (m_Wrapper.m_SelectionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISelectionActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SelectionActions @Selection => new SelectionActions(this);
    public interface ICameraActions
    {
        void OnYaw(InputAction.CallbackContext context);
        void OnPitch(InputAction.CallbackContext context);
        void OnRTSView(InputAction.CallbackContext context);
        void OnXZMove(InputAction.CallbackContext context);
        void OnYMove(InputAction.CallbackContext context);
        void OnMiddleMouseMove(InputAction.CallbackContext context);
    }
    public interface IEntitiesActions
    {
        void OnSpeed(InputAction.CallbackContext context);
        void OnHeading(InputAction.CallbackContext context);
        void OnCommand(InputAction.CallbackContext context);
        void OnIntercept(InputAction.CallbackContext context);
        void OnCreate100(InputAction.CallbackContext context);
        void OnAddCommand(InputAction.CallbackContext context);
    }
    public interface ISelectionActions
    {
        void OnClearSelection(InputAction.CallbackContext context);
        void OnCursor(InputAction.CallbackContext context);
        void OnCursorPosition(InputAction.CallbackContext context);
        void OnNextEntity(InputAction.CallbackContext context);
    }
}
